Vagrant.configure("2") do |config|
  config.vm.hostname = "control-node"
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_udp:false
  config.vm.provision "shell", path:'provision.sh'
end
