Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "provision.sh"
  config.vm.box = "centos/7"  
  config.vm.network "private_network", ip: "192.168.56.20"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_udp: false

end
